[package]
name = "mons-dot-rehab"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "mons_dot_rehab"

[features]
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.29.0"